version: '3'
services: 
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_etl
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

volumes:
  postgres_data: